Modular testing setup
McModLauncher/modlauncher pull request #101
Opened 2022-03-03 17:50 UTC by Su5eD

## Launching without BootstrapLauncher
The first step to running tests is being able to launch modlauncher without BootstrapLancher so that we can 

## Modular Unit tests

## JMH Benchmark

2022-03-06 19:37 UTC, cpw commented
Nice, thank you sir. I'll take a look at merging it in. Having test harnesses back will improve many things, not just ModLauncher.

2022-03-21 08:27 UTC, OrionDevelopment requested changes
Besides a minor comment on the reason for changing the module layer: This looks okey. Could you please add the requested comment?

2022-03-21 08:27 UTC, OrionDevelopment commented on src/main/java/cpw/mods/modlauncher/ModuleLayerHandler.java
> +        completedLayers.put(Layer.BOOT, new LayerInfo(getClass().getModule().getLayer(), cl));
Could you please document why this change was made?

2022-03-21 08:29 UTC, OrionDevelopment commented
Also as you can see from the attached build log, your tests are failing @Su5eD could you take a look and fix those.
[ModLauncher_Pull_Requests_9.1.10.log](https://github.com/McModLauncher/modlauncher/files/8313982/ModLauncher_Pull_Requests_9.1.10.log)

2022-03-21 21:48 UTC, Su5eD commented
The TransformingClassLoaderTests class requires [SecureJarHandler#25](https://github.com/McModLauncher/securejarhandler/pull/25) to pass due to the way SecureJarHandler handles package lookups. Please see the PR for the full issue explanation.

2022-03-23 18:13 UTC, OrionDevelopment commented
With McModLauncher/Securejarhandler#25 merged what does this need to run @Su5eD ?

2022-03-23 18:28 UTC, Su5eD commented
It should run fine now, assuming CI picks up the new SJH release

2022-05-02 18:58 UTC, OrionDevelopment approved these changes

2022-05-02 18:58 UTC, merged