[CVE-2021-44228]: Update Log4J to resolve security issues
McModLauncher/modlauncher pull request #77
Opened 2021-12-10 15:37 UTC by Gamebuster19901

Also: Is it possible to get this backported to earlier versions of modlauncher? The vulnerability is propagated downstream.

2021-12-10 16:44 UTC, OrionDevelopment commented
Thanks for the Pull Request, this problem has been fixed in the downstream systems and is not really a hot issue in this project.
That is, unless somebody is running without forge or fml, which we are not aware of.

We will merge this PR eventually when another round of bugfixes for this project get merged, or unless this priority requires more attention.

2021-12-10 17:06 UTC, Gamebuster19901 commented
I use modlauncher in some of my projects, outside of a minecraft environment. I'm forced to stay on version 8.0.9 due to a 3 way incompatability with java 11, mixin, and modlauncher.

 I suppose I can specify the exact log4j version to use if you guys don't want to make another release right now, or backport the fix.

2021-12-10 18:44 UTC, OrionDevelopment commented
Okey Bump @cpw

2021-12-17 03:08 UTC, Gamebuster19901 commented
Looks like mojang is moving away from log4j and switching to slf4j

https://github.com/Mojang/DataFixerUpper/pull/60

2021-12-21 21:05 UTC, sciwhiz12 requested changes
Please update this to 2.17.0, as that is now the latest version.

2021-12-22 07:12 UTC, OrionDevelopment approved these changes

2021-12-22 09:33 UTC, sciwhiz12 approved these changes

2021-12-29 20:10 UTC, cpw commented
I'd like to move to using slf4j or other simple logger abstraction library where possible...

2021-12-29 20:49 UTC, sciwhiz12 commented
Moving away from Log4J may be a bit problematic, because ModLauncher provides a pattern converter plugin in [`TransformingThrowablePatternConverter`](https://github.com/McModLauncher/modlauncher/blob/9943aea36214c37fe775d3d1a53bb4cab064e39e/src/main/java/cpw/mods/modlauncher/log/TransformingThrowablePatternConverter.java) for adding the audit trail to stacktraces of throwables. 

SLF4J does not provide an equivalent API, so either we dual-include both SLF4J API (for actual logging) and Log4j (for the pattern converter), only SLF4J (which means the pattern converter is lost or needs to be moved out into a separate artifact/repo), or Log4j only (which means this PR is still needed).

2021-12-29 21:04 UTC, sciwhiz12 requested changes
Please update this to 2.17.1, as that is now the latest version.

2021-12-31 01:34 UTC, sciwhiz12 requested changes
Please recreate and GPG-sign these commits, as the branch protection rule indicates.

2021-12-31 03:17 UTC, Gamebuster19901 commented
Sorry, but I'm not doing that. I don't have a GPG key. It's not worth the effort just for 3 lines in a config file. An admin can override the branch protection, or someone with a key can recreate this PR

2021-12-31 04:07 UTC, Gamebuster19901 commented
Supersceded by #79

2021-12-31 04:07 UTC, closed without merging